[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 测试选项
# -v: 详细输出
# -s: 显示标准输出
# --tb=short: 短格式跟踪信息
# --reruns 2: 重试次数
# --reruns-delay 1: 重试延迟时间
# --alluredir=./temps: 生成 Allure 报告目录
# --clean-alluredir: 清理 Allure 报告目录
addopts = -v -s --tb=short --reruns 2 --reruns-delay 1 --alluredir=./temps --clean-alluredir

markers =
    smoke: 冒烟测试
    critical: 核心功能（阻塞发布）
    slow: 耗时用例（可选跑）
    regression: 回归测试
    api: api 测试用例
    web: web ui 测试用例
