[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = -v -s --tb=short

markers =
	smoke: smoke test
	critical: critical feature (block release)
	slow: slow test case
	regression: regression test
	api: api test case
	web: web ui test case
